// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MirasPaylasim.Data;

#nullable disable

namespace MirasPaylasim.Data.Migrations
{
    [DbContext(typeof(MirasContext))]
    [Migration("20251006143447_Initial_TR")]
    partial class Initial_TR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MirasPaylasim.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Debts")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasGrandchildrenFromPredeceasedChild")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPredeceasedChild")
                        .HasColumnType("bit");

                    b.Property<int>("LivingChildrenCount")
                        .HasColumnType("int");

                    b.Property<int>("ParentsAlive")
                        .HasColumnType("int");

                    b.Property<string>("PredeceasedChildNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Receivables")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpouseDeathTiming")
                        .HasColumnType("int");

                    b.Property<int>("SpouseStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAssets")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hesaplamalar", (string)null);
                });

            modelBuilder.Entity("MirasPaylasim.Models.Share", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CalculationId")
                        .HasColumnType("int");

                    b.Property<int>("FractionDenominator")
                        .HasColumnType("int");

                    b.Property<int>("FractionNumerator")
                        .HasColumnType("int");

                    b.Property<string>("HeirDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeirType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.ToTable("Paylar", (string)null);
                });

            modelBuilder.Entity("MirasPaylasim.Models.Share", b =>
                {
                    b.HasOne("MirasPaylasim.Models.Calculation", "Calculation")
                        .WithMany("Shares")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("MirasPaylasim.Models.Calculation", b =>
                {
                    b.Navigation("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
